name: azs_app
description: Учёт заявок и ТО по АЗС (Новгород + Санкт-Петербург)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  excel: ^4.0.6
  share_plus: ^10.1.4
  http: ^1.2.2
  flutter_dotenv: ^5.2.1
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  url_launcher: ^6.3.1
  webviewimage: ^0.0.6
  intl: ^0.20.2
  archive: ^3.6.1
  ntk_map_view:
    path: ../../EdetGruz/edet_gruz/packages/ntk_map_view
  firebase_core: ^4.13.0
  cloud_firestore: ^6.8.0
  firebase_auth: ^6.5.7
  connectivity_plus: ^7.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app_icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/app_icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/stations_yandex.json
    - assets/operational_data.json
    - assets/station_equipment.json
    - assets/templates/defect_act_template.docx
    - .env
